### ISSUE TITLE
Limited prompt

### ISSUE THREAD

**Issue by workpioupiou** [nod-ai/SHARK#1686]
Is that normal that prompt are trunkated ?

**Comment by NeedsMoar** [comment]
If you mean at 64 / 77 tokens, then yes.  The "infinite prompt" thing is an extension in automatic1111 and such that splits longer prompts and feeds them into the model in stages.

**Comment by one-lithe-rune** [comment]
Shark should currently detect and build a different unet if you go over 64 / 77 token, that supports a longer prompts and uses that. (I think up to 512? The .vmfb files get `unet512` in the naming rather than just `unet`, but I'm not super sure of how it works).

It doesn't use that unet by default as that one creates somewhat different images to the 64 / 77 version with the same seed even when a longer prompt isn't needed.

**Comment by NeedsMoar** [comment]
That's odd.  I'm guessing I'm going over most of the time without knowing it.  Looking at my built .vmfbs most are using unet512.  At the same time I've had it error out saying the model could only handle 64/77 tokens when the prompt was nowhere near 512 tokens, so I'm not sure.  I think this only happened when I had a really long negative prompt, so it's possible only the positive prompt is checked to see which it should use?  I searched the codebase for related terms and saw quite a bit about unet512 upconvert in the chat models but not in diffusers.
