### ISSUE TITLE
URL in LoRA Training README Leads to Nothing

### ISSUE THREAD

**Issue by njsharpe** [nod-ai/SHARK#1762]
Document: https://github.com/nod-ai/SHARK/blob/main/shark/examples/shark_training/stable_diffusion/README.md
URL in Question: https://github.com/nod-ai/SHARK#how-to-use-your-locally-built-iree--torch-mlir-with-shark

What did this used to point to? Is it still needed?

**Comment by NeedsMoar** [comment]
I gave up on it; aside from the mess of building a cherry-picked llvm-iree merge (why not just provide a binary?), the training files included need to be modified because they'll immediately attempt to default to CUDA.  

Search the web for LoRA training CoLAB and you can get free access to a trainer running on oldish NVidia hardware that'll train to ~3000 iterations in about 15 minutes, which is approximately 200 hours less than it'll take you to get anything LLVM related that's not explicitly documented working correctly.  I decided that there was too good a chance of a non tuned training path running like hot garbage after doing all the work since there aren't any benchmarks available of it, similar to trying to generate 640x640 images or anything else that doesn't have an explicit tuning config in torch.

**Comment by njsharpe** [comment]
Eh, works for me. I knew about the online CoLAB route and have explored it briefly but was wondering if I could use a native solution. It might be worth it to clean up the LoRA stuff if it's not going to be explored more, but I'll leave that to your or the team's discretion.

Closing as answered.
