### ISSUE TITLE
Failure on linux with winreg and tkinter usage

### ISSUE THREAD

**Issue by PhaneeshB** [nod-ai/SHARK#1962]
Hey @one-lithe-rune Thanks for your contribution in #1952 ! 

There's just some missing dependency for winreg and tkinter on top of main branch in SHARK

This is what I have (I'm on a linux system)
command - `python apps/stable_diffusion/web/index.py --share`
error
```
ModuleNotFoundError: No module named 'winreg'
``` 
same thing happens with the tkinter import too.

---
After googling for a bit it seems like we would need pip installable substitutes for these
which will need to be added to [requirements.txt](https://github.com/nod-ai/SHARK/blob/main/requirements.txt)

I see `tk` already a part of the venv, and 
[`winregistry`](https://pypi.org/project/winregistry/) seems to be what can be used?

**Comment by one-lithe-rune** [comment]
Hmmm, I wonder why I'm not seeing that with winreg? 

I though it was built in: https://docs.python.org/3/library/winreg.html

Are you on Linux or Mac? If so, maybe the problem is that I need to move both the imports into the functions that use them so they won't be encountered unless you're on windows. The function that does the registry checking stuff does have a guard clause for win32.

I'll push a commit that does that in the first instance.
