### ISSUE TITLE
Move command history into WebUI

### ISSUE THREAD

**Issue by nirvedhmeshram** [nod-ai/SHARK#789]
This way the WebUI users do not have to deal with command window

**Comment by powderluv** [comment]
folks want the history file in the directory with the generated images

**Comment by Suplexxer** [comment]
might i post a usecase. feel free to disregard or scrap post.
im tinking with different promts and CFGs to make beautifull city landscapes. i take a break from it for a day and return. its hard to know where i left off when i cant link the image to the promt used. i would want to know the model, steps, prompt, negative prompt, seed, CFG scale and which scheduler. right know i get all that in the excel file but having created 50ish images its impossible to sort through trying to remember which image came from which prompt. since i might be using the same seed but different promts.

**Comment by powderluv** [comment]
I think this already added an png metadata. We can open new issues to track anything more we need.
